--Datefunction--

--sysdate--

select TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS') AS current_date

select sysdate from dual;

--current_date--

select current_date from dual;

SELECT 
    TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS') AS current_date_time_1,
    TO_CHAR(CURRENT_DATE, 'DD-MM-YYYY HH24:MI:SS') AS current_date_time_2
FROM dual;



--ADD MONTHS--

SYNTAX: SELECT ADD_MONTHS(DATE TYPE VALUE,NUMBER VALUE)
EX:
SELECT ADD_MONTHS('14-JAN-2020',9) FROM DUAL;

SELECT ADD_MONTHS('14-FEB-2020',10.84) FROM DUAL;

SELECT ADD_MONTHS('14-FEB-2020',-9) FROM DUAL;

--MONTHS_BETWEEN--

SYNTAX: SELECT MONTHS_BETWEEN(date1,date2)

SELECT MONTHS_BETWEEN('21-FEB-2021','o2-JAN-2020') FROM DUAL;

select MONTHS_BETWEEN('10-jan-2025','10-jan-2024')from dual;

--NEXT DAY--

SYNTAX: SELECT NEXT_DAY(DATE,WEEK-DAY)

SELECT NEXT_DAY('10-JAN-2025','THURSEDAY') FROM DUAL;
SELECT NEXT_DAY('10-FEB-2025','MONDAY') FROM DUAL;

--LAST DAY--

SYNTAX: SELECT LAST_DAY(DATE)

SELECT LAST_DAY('21-SEP-2025') FROM DUAL;

SELECT LAST_DAY('18-May-2025') FROM DUAL;

SELECT LAST_DAY('01-JUNE-2024') FROM DUAL;




